use sql_project;
# basic questions
-- Q1. most senior employee based on the job title
select *from employee order by title DESC;
-- employee- Jane Peacock and job_title - Sales Support Agent

-- Q2. which country has the most invoices
select billing_country,count(invoice_id) as total_invocies
from invoice 
group by billing_country;
select* from invoice order by total_invocies desc;

-- USA  has the most number of invocies(131)

-- Q3 identify the top 3 invocies total
select * from invoice order by total desc;
-- top 3 invoices total are invoice_id 183,31,92 respectively total is 23.7599,19.8,19.8

-- Q4 City with the highest total invoice amount to determine the best location for a promotional event
select billing_city ,sum(total) as total_invoice_amount
from invoice
group by billing_city
order by total_invoice_amount desc
limit 1;
-- Prague is the best city for permotional event (total_invoice_amount is 273.2400)

-- Q5. identify the customer who has spent most money
select customer.customer_id ,customer.first_name,customer.last_name,sum(invoice.total) as total_spent
from customer 
join invoice
on customer.customer_id=customer.customer_id
group by customer.customer_id,customer.first_name,customer.last_name
order by total_spent desc
limit 1;
-- Rishabh  Mishra has the spent most money 4709.429999

-- MODERATE QUESTIONS

-- Q1. FIND EMAIL,FIRST NAME,LAST NAME OF CUSTOMERS WHO LISTEN ROCK MUSIC
SELECT CUSTOMER.CUSTOMER_ID ,CUSTOMER.FIRST_NAME,CUSTOMER.LAST_NAME,CUSTOMER.EMAIL 
FROM CUSTOMER
JOIN INVOICE
ON CUSTOMER.CUSTOMER_ID=CUSTOMER.CUSTOMER_ID
JOIN INVOICE_LINE
ON INVOICE.INVOICE_ID=INVOICE_LINE.INVOICE_ID
JOIN TRACK
ON INVOICE_LINE.TRACK_ID=TRACK.TRACK_ID
JOIN GENRE
ON TRACK.GENRE_ID=GENRE.GENRE_ID
WHERE GENRE.NAME="ROCK";

-- Q2 TOP 10 ROCK ARTISTS BASED ON TRACK COUNT
SELECT ARTIST.ARTIST_ID,ARTIST.NAME ,COUNT(TRACK.TRACK_ID) AS TRACK_COUNT
FROM ARTIST
JOIN ALBUM2
ON ARTIST.ARTIST_ID=ALBUM2.ARTIST_ID
JOIN TRACK
ON ALBUM2.ALBUM_ID=TRACK.ALBUM_ID
JOIN GENRE
ON TRACK.GENRE_ID=GENRE.GENRE_ID
WHERE GENRE.NAME="ROCK"
group by ARTIST.ARTIST_ID,ARTIST.NAME
ORDER BY TRACK_COUNT DESC
LIMIT 10;

-- Q3 ALL TRACK NAMES WHICH ARE LONGER THAN THE AVG TRACK LENGTH

SELECT NAME,milliseconds
FROM TRACK
WHERE milliseconds>(SELECT AVG(milliseconds)
FROM TRACK)
ORDER BY milliseconds;

-- ADVANCED QUESTIONS

-- Q1. CALCULATE HOW MUCH EACH CUSTOMER HAS SPENT ON EACH ARTIST
-- use of CTE
WITH ARTIST_SALES AS(
SELECT INVOICE.CUSTOMER_ID,
ARTIST.ARTIST_ID,ARTIST.NAME,
SUM(INVOICE_LINE.UNIT_PRICE*INVOICE_LINE.QUANTITY) AS TOTAL_SPENT
FROM INVOICE_LINE 
JOIN INVOICE
ON INVOICE.INVOICE_ID=INVOICE_LINE.INVOICE_ID
JOIN TRACK
ON INVOICE_LINE.TRACK_ID=TRACK.TRACK_ID
JOIN ALBUM2
ON TRACK.ALBUM_ID=ALBUM2.ALBUM_ID
JOIN ARTIST
ON ALBUM2.ARTIST_ID=ARTIST.ARTIST_ID
GROUP BY
INVOICE.CUSTOMER_ID,
ARTIST.ARTIST_ID,
ARTIST.NAME
)
SELECT 
CUSTOMER.CUSTOMER_ID,
CUSTOMER.FIRST_NAME,
CUSTOMER.LAST_NAME,
ARTIST_SALES.NAME,
ARTIST_SALES.TOTAL_SPENT
FROM ARTIST_SALES
JOIN CUSTOMER
ON ARTIST_SALES.CUSTOMER_ID=CUSTOMER.CUSTOMER_ID
ORDER BY
CUSTOMER.CUSTOMER_ID,
ARTIST_SALES.TOTAL_SPENT DESC;
-- MAX SPENT ON THE AC/DC ARTIST BY CUSTOMER LuÃ­s GonÃ§alves TOTAL_SPENT 7.920000

-- Q2: Determine the most popular music genre for each country based on purchases.
WITH GENRE_PURCHASES AS(
SELECT CUSTOMER.COUNTRY,GENRE.NAME AS GENRE_NAME,
COUNT(INVOICE_LINE.QUANTITY) AS TOTAL_PURCHASES 
FROM INVOICE_LINE
JOIN INVOICE
ON INVOICE.INVOICE_ID=INVOICE_LINE.INVOICE_ID
JOIN CUSTOMER
ON INVOICE.CUSTOMER_ID=CUSTOMER.CUSTOMER_ID
JOIN TRACK
ON INVOICE_LINE.TRACK_ID=TRACK.TRACK_ID
JOIN GENRE
ON TRACK.GENRE_ID=GENRE.GENRE_ID
GROUP BY
CUSTOMER.COUNTRY,GENRE_NAME
),
RANKED_GENRES AS(
SELECT 
COUNTRY,
GENRE_NAME,
TOTAL_PURCHASES,
RANK() OVER (
PARTITION BY COUNTRY 
ORDER BY TOTAL_PURCHASES DESC)
AS RANK_GENRE 
FROM GENRE_PURCHASES)
SELECT COUNTRY,GENRE_NAME,TOTAL_PURCHASES
FROM RANKED_GENRES
WHERE RANK_GENRE=1
ORDER BY COUNTRY;

-- Q3 Identify the top-spending customer for each country.
-- 1ST STEP CALCULATE TOTAL SPENDING OF EACH CUSTOMER
WITH CUSTOMERS_SPENDING AS (
SELECT
CUSTOMER.CUSTOMER_ID,
CUSTOMER.FIRST_NAME,
CUSTOMER.LAST_NAME,
CUSTOMER.COUNTRY,
SUM(INVOICE.TOTAL) AS TOTAL_SPENT
FROM  CUSTOMER
JOIN INVOICE
ON INVOICE.CUSTOMER_ID=CUSTOMER.CUSTOMER_ID
GROUP BY
CUSTOMER.CUSTOMER_ID,
CUSTOMER.FIRST_NAME,
CUSTOMER.LAST_NAME,
CUSTOMER.COUNTRY
)
-- 2ND PART 
,RANKED_CUSTOMER AS (
SELECT
*,
RANK() OVER(
PARTITION BY COUNTRY
ORDER BY TOTAL_SPENT DESC
) AS SPENDING_RANK
FROM CUSTOMERS_SPENDING
)
SELECT 
COUNTRY,
FIRST_NAME,
LAST_NAME,
TOTAL_SPENT
FROM RANKED_CUSTOMER
WHERE SPENDING_RANK=1
ORDER BY COUNTRY;



